name: Lint test

on: pull_request

jobs:
  lint-test:
    name: Next Lint test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm i -g pnpm
      - run: pnpm i
      - run: pnpm lint